apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: iid
  namespace: kube-system
spec:
  forwardAuth:
    address: http://traefik-forward-iid.kube-system:4181
    authResponseHeaders:
    - X-Forwarded-User
    - Authorization
